---
- name: EC2
  hosts: ec2
  become: yes
  tasks:
    - name: stop Docker service
      service:
        name: docker
        state: stopped
        enabled: false

    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start Apache service
      service:
        name: httpd
        state: started

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted

    - name: Copy local directory to remote server
      copy:
        src: "../hello-2048/public_html/"
        dest: "/var/www/html/"
        owner: apache
        group: apache
        mode: 0755

